# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mdwa_planning/Environment.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mdwa_planning.msg

class Environment(genpy.Message):
  _md5sum = "366bf54a33961c132c7cb18ef82cb2bb"
  _type = "mdwa_planning/Environment"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """mdwa_planning/Barrier[] barrier
mdwa_planning/Dy_Barrier[] dy_obs
float32 obs_size

================================================================================
MSG: mdwa_planning/Barrier
float64 x
float64 y

================================================================================
MSG: mdwa_planning/Dy_Barrier
float64 x
float64 y
float64 vx
float64 vy
"""
  __slots__ = ['barrier','dy_obs','obs_size']
  _slot_types = ['mdwa_planning/Barrier[]','mdwa_planning/Dy_Barrier[]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       barrier,dy_obs,obs_size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Environment, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.barrier is None:
        self.barrier = []
      if self.dy_obs is None:
        self.dy_obs = []
      if self.obs_size is None:
        self.obs_size = 0.
    else:
      self.barrier = []
      self.dy_obs = []
      self.obs_size = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.barrier)
      buff.write(_struct_I.pack(length))
      for val1 in self.barrier:
        _x = val1
        buff.write(_get_struct_2d().pack(_x.x, _x.y))
      length = len(self.dy_obs)
      buff.write(_struct_I.pack(length))
      for val1 in self.dy_obs:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.vx, _x.vy))
      _x = self.obs_size
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.barrier is None:
        self.barrier = None
      if self.dy_obs is None:
        self.dy_obs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.barrier = []
      for i in range(0, length):
        val1 = mdwa_planning.msg.Barrier()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _get_struct_2d().unpack(str[start:end])
        self.barrier.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dy_obs = []
      for i in range(0, length):
        val1 = mdwa_planning.msg.Dy_Barrier()
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.vx, _x.vy,) = _get_struct_4d().unpack(str[start:end])
        self.dy_obs.append(val1)
      start = end
      end += 4
      (self.obs_size,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.barrier)
      buff.write(_struct_I.pack(length))
      for val1 in self.barrier:
        _x = val1
        buff.write(_get_struct_2d().pack(_x.x, _x.y))
      length = len(self.dy_obs)
      buff.write(_struct_I.pack(length))
      for val1 in self.dy_obs:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.vx, _x.vy))
      _x = self.obs_size
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.barrier is None:
        self.barrier = None
      if self.dy_obs is None:
        self.dy_obs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.barrier = []
      for i in range(0, length):
        val1 = mdwa_planning.msg.Barrier()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _get_struct_2d().unpack(str[start:end])
        self.barrier.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.dy_obs = []
      for i in range(0, length):
        val1 = mdwa_planning.msg.Dy_Barrier()
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.vx, _x.vy,) = _get_struct_4d().unpack(str[start:end])
        self.dy_obs.append(val1)
      start = end
      end += 4
      (self.obs_size,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
