// Generated by gencpp from file mdwa_planning/Barrier.msg
// DO NOT EDIT!


#ifndef MDWA_PLANNING_MESSAGE_BARRIER_H
#define MDWA_PLANNING_MESSAGE_BARRIER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mdwa_planning
{
template <class ContainerAllocator>
struct Barrier_
{
  typedef Barrier_<ContainerAllocator> Type;

  Barrier_()
    : x(0.0)
    , y(0.0)  {
    }
  Barrier_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::mdwa_planning::Barrier_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mdwa_planning::Barrier_<ContainerAllocator> const> ConstPtr;

}; // struct Barrier_

typedef ::mdwa_planning::Barrier_<std::allocator<void> > Barrier;

typedef boost::shared_ptr< ::mdwa_planning::Barrier > BarrierPtr;
typedef boost::shared_ptr< ::mdwa_planning::Barrier const> BarrierConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mdwa_planning::Barrier_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mdwa_planning::Barrier_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mdwa_planning::Barrier_<ContainerAllocator1> & lhs, const ::mdwa_planning::Barrier_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mdwa_planning::Barrier_<ContainerAllocator1> & lhs, const ::mdwa_planning::Barrier_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mdwa_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mdwa_planning::Barrier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mdwa_planning::Barrier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mdwa_planning::Barrier_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mdwa_planning::Barrier_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mdwa_planning::Barrier_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mdwa_planning::Barrier_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mdwa_planning::Barrier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::mdwa_planning::Barrier_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mdwa_planning::Barrier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mdwa_planning/Barrier";
  }

  static const char* value(const ::mdwa_planning::Barrier_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mdwa_planning::Barrier_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::mdwa_planning::Barrier_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mdwa_planning::Barrier_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Barrier_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mdwa_planning::Barrier_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mdwa_planning::Barrier_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MDWA_PLANNING_MESSAGE_BARRIER_H
